 version: "3.8"
 networks:
   mynetwork:
 services:
   userInterface:
     image: php:7.4-apache
     networks:
       - mynetwork
     ports:
       - "8080:80"
     volumes:
       - "./UserInterface:/var/www/html"
   authmanager:
     build:
       context: ./Auth
     volumes:
       - "./Auth:/usr/src/app"
     networks:
       - mynetwork
     ports:
       - "8081:42069"
   mongo:
     image: mongo
     command: --nojournal
     networks:
       - mynetwork
     ports:
       - "8082:27017"
     volumes:
       - ./mongoVolume:/data/db
   node:
     build:
       context: ./PlayMaster
     volumes:
       - ./PlayMaster:/home/node/app
     ports:
       - "8083:8081"
     command: "node init.js"